/**
 * Cloudflare Worker entry — routes apex vs restaurant subdomains before Next.js.
 *
 * Root domain (halalresmenu.com / www): pass through to Next.js with NO x-subdomain.
 * Restaurant subdomain ({slug}.halalresmenu.com): set x-subdomain for middleware rewrite.
 */
import {
  extractRestaurantSubdomain,
  hostnameOnly,
  isApexHost,
} from "../lib/host-routing";
import { fetchWithEdgeCache } from "./edge-cache";

// Generated by `npm run worker:build` (@cloudflare/next-on-pages)
// @ts-expect-error — build artifact, present after worker:build
import nextOnPagesHandler from "../.worker-next/index.mjs";

interface Env {
  NEXT_PUBLIC_ROOT_DOMAIN?: string;
}

function prepareRequest(request: Request, env: Env): Request {
  const url = new URL(request.url);
  const rootDomain = env.NEXT_PUBLIC_ROOT_DOMAIN;

  const hostname = hostnameOnly(
    request.headers.get("x-forwarded-host") ??
      request.headers.get("host") ??
      url.hostname
  );

  const headers = new Headers(request.headers);
  headers.set("x-forwarded-host", hostname);

  const subdomain = extractRestaurantSubdomain(hostname, rootDomain);

  if (subdomain) {
    headers.set("x-subdomain", subdomain);
  } else {
    headers.delete("x-subdomain");
  }

  if (
    isApexHost(hostname, rootDomain) &&
    (url.pathname === "/sitemap_index.xml" ||
      url.pathname === "/sitemap_index.xml/")
  ) {
    url.pathname = "/sitemap.xml";
  }

  return new Request(url.toString(), {
    method: request.method,
    headers,
    body: request.body,
    redirect: request.redirect,
  });
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: { waitUntil: (promise: Promise<unknown>) => void; passThroughOnException?: () => void }
  ): Promise<Response> {
    const prepared = prepareRequest(request, env);

    return fetchWithEdgeCache(
      prepared,
      env.NEXT_PUBLIC_ROOT_DOMAIN,
      () => nextOnPagesHandler.fetch(prepared, env, ctx),
      ctx
    );
  },
};
